import test from 'node:test';import assert from 'node:assert/strict';
import {apply,initialState as createState,actions,projectSucceeded} from '../skills/woia-technology-operations/scripts/provider.mjs';
const initialState=()=>createState('org','scope');
import {digest,beginEffect,dispatchPending,reconcileEffect} from '../skills/woia-technology-operations/scripts/authority-effect.mjs';
function command(action='technology.change.execute',payload={change_id:'chg',recovery_plan:'plan',expected_target_revision:'r1'}){return{action,organization:'org',scope:'scope',resource_id:'camp',effect_id:'e1',expected_revision:0,payload}}
function auth(c){return{authenticated:true,organization:'org',scope:'scope',task_id:'t',actor_id:'actor',department:'Technology',writer:'Technology',now:10,expires_at:100,source_current:true,conflict:false,actions:[...actions],policy_revision:'p1',binding_revision:'b1',authority_revision:'a1',approval:{approver:'human',result:'APPROVED',command_digest:digest(c),policy_revision:'p1',binding_revision:'b1',authority_revision:'a1',expires_at:99}}}
test('all required actions exported',()=>assert.equal(actions.length,10));
test('CAS rejection never invokes adapter',async()=>{const c=command(),a=auth(c),s=beginEffect(initialState(),c,a,'Technology').state;let calls=0;await assert.rejects(dispatchPending(s,c,a,'Technology',{qualification:'PASS',binding_revision:'b1',persist:async()=>false,execute:async()=>{calls++}}),/DURABLE_CAS/);assert.equal(calls,0)});
test('state isolation rejects another organization',()=>{const c=command(),s=initialState();s.organization='other';assert.throws(()=>apply(s,c,auth(c)),/STATE_SCOPE/)});
test('read still requires current explicit grant',()=>{const c=command('technology.binding.read',{});const a=auth(c);a.department='Other';assert.doesNotThrow(()=>apply(initialState(),c,a));a.actions=[];assert.throws(()=>apply(initialState(),c,a),/ACTION/)});
test('valid exact effect stages without input mutation',()=>{const c=command(),s=initialState(),r=apply(s,c,auth(c));assert.equal(r.effect.status,'PENDING');assert.equal(s.revision,0);assert.equal(r.state.revision,1)});
for(const [name,change] of [['wrong owner',a=>a.department='Other'],['revoked',a=>a.revoked=true],['hold',a=>a.hold=true],['stale source',a=>a.source_current=false],['conflict',a=>a.conflict=true],['wrong scope',a=>a.scope='other'],['self approval',a=>a.approval.approver='actor'],['changed binding',a=>a.binding_revision='b2'],['expiry',a=>a.now=200],['unauthenticated',a=>a.authenticated=false],['no action grant',a=>a.actions=[]]]){
test('reject '+name,()=>{const c=command(),a=auth(c);change(a);assert.throws(()=>apply(initialState(),c,a))})}
test('payload change invalidates approval',()=>{const c=command(),a=auth(c);c.payload.extra='changed';assert.throws(()=>apply(initialState(),c,a),/EXACT_APPROVAL/)});
test('stale expected revision blocks',()=>{const c=command();c.expected_revision=9;assert.throws(()=>apply(initialState(),c,auth(c)),/REVISION/)});
test('same identity never blindly dispatches again',()=>{const c=command(),a=auth(c),r=beginEffect(initialState(),c,a,'Technology');r.state.revision=0;r.state.effects['org/scope/e1'].status='UNKNOWN';assert.equal(beginEffect(r.state,c,a,'Technology').dispatch,false)});
test('idempotency conflicts rejected',()=>{const c=command(),r=beginEffect(initialState(),c,auth(c),'Technology');r.state.revision=0;c.payload.changed=true;assert.throws(()=>beginEffect(r.state,c,auth(c),'Technology'),/IDEMPOTENCY/)});
test('unknown durably retained before network failure',async()=>{const c=command(),a=auth(c),s=beginEffect(initialState(),c,a,'Technology').state;let saved;const r=await dispatchPending(s,c,a,'Technology',{qualification:'PASS',binding_revision:'b1',persist:async n=>{saved=n;return true},execute:async()=>{assert.equal(saved.effects['org/scope/e1'].status,'UNKNOWN');throw Error('network')}});assert.equal(r.effects['org/scope/e1'].status,'UNKNOWN');await assert.rejects(dispatchPending(r,c,a,'Technology',{}),/PENDING/)});
test('unqualified port fails before contact',async()=>{const c=command(),a=auth(c),s=beginEffect(initialState(),c,a,'Technology').state;await assert.rejects(dispatchPending(s,c,a,'Technology',{qualification:'NOT_RUN'}),/QUALIFIED/)});
test('reconciliation requires attributable matching evidence',()=>{const c=command(),s=beginEffect(initialState(),c,auth(c),'Technology').state;const rc={...c,action:'technology.recovery.reconcile',expected_revision:1,payload:{effect_id:'e1',status:'SUCCEEDED',source_id:'source',evidence_id:'evidence'}};assert.equal(reconcileEffect(s,rc,auth(rc),'Technology').effects['org/scope/e1'].status,'SUCCEEDED');delete rc.payload.evidence_id;assert.throws(()=>reconcileEffect(s,rc,auth(rc),'Technology'),/ATTRIBUTED/)});
test('restore preserves revocations/external effect boundaries',()=>{const c=command('technology.restore.execute',{backup_id:'backup',backup_checksum:'hash',reconciliation_plan:'plan',preserve_revocations:true,external_effects_rollback:false});const r=apply(initialState(),c,auth(c));r.state.access.person={revoked:true};r.state.effects['org/scope/e1'].status='SUCCEEDED';assert.equal(projectSucceeded(r.state,'e1','org','scope').access.person.revoked,true);c.payload.external_effects_rollback=true;assert.throws(()=>apply(initialState(),c,auth(c)),/RESTORE/)});
test('training does not grant access',()=>{const c=command('technology.access.apply',{subject_id:'person',permissions:['read'],expires_at:80,training:'complete'});assert.throws(()=>apply(initialState(),c,auth(c)),/ACCESS_CONTRIBUTION/)});
test('observations require evidence and remain separate',()=>{const c=command('technology.health.observe',{source_id:'src',evidence_id:'ev',observed_at:1,status:'UNKNOWN'});const r=apply(initialState(),c,auth(c));assert.equal(r.state.observations.length,1);assert.equal(Object.keys(r.state.effects).length,0)})
